export const {
    AlarmAbsolute,
    AlarmRelative,
    ApplicationControl,
    ApplicationControlData,
    AttributeFilter,
    AttributeRangeFilter,
    Bundle,
    CompositeFilter,
    DownloadRequest,
    ExifInformation,
    IotconOption,
    Query,
    Representation,
    Response,
    SimpleCoordinates,
    SortMode,
    TZDate,
    TimeDuration,
    VoiceControlCommand,
    account,
    alarm,
    application,
    archive,
    content,
    datacontrol,
    download,
    exif,
    filesystem,
    iotcon,
    keymanager,
    mediacontroller,
    messageport,
    push,
    systeminfo,
    time,
    tvaudiocontrol,
    tvdisplaycontrol,
    tvinfo,
    tvinputdevice,
    tvwindow,
    voicecontrol,
    websetting
} = window.tizen;

const pkg = window.tizen.package;
export { pkg as package };
